modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="cherry_village"
version="${forge_mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''


[[dependencies.cherry_village]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.cherry_village]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"